In [ ]:
# WORKING ON NUMPY ARRAY

In [1]:
import numpy as np

In [2]:
#How Generate a np array of vector of length 50 and two dimensional of shape 4x5 uniformly distributed between 0 and 1
vect=np.linspace(0, 1, 50 )
vect

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [7]:
# two dimensional shape 4x5 uniformly distributed between 0 and 1
val = np.linspace(0, 1, 20)
val

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [7]:
val=val.reshape(4,5)
val

array([[0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632],
       [0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421],
       [0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211],
       [0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ]])

In [10]:
# spliting the two dimension array into three arrays taking the first two rows, follow by the next two rows and put the 
# remaining in another variable
first, second, third = np.vsplit(val, [2,4])
print("var1\n",first)
print("var2\n", second)
print("var3\n",third)

var1
 [[0.         0.05263158 0.10526316 0.15789474 0.21052632]
 [0.26315789 0.31578947 0.36842105 0.42105263 0.47368421]]
var2
 [[0.52631579 0.57894737 0.63157895 0.68421053 0.73684211]
 [0.78947368 0.84210526 0.89473684 0.94736842 1.        ]]
var3
 []


In [8]:
val1=val.reshape(5,4)
val1

array([[0.        , 0.05263158, 0.10526316, 0.15789474],
       [0.21052632, 0.26315789, 0.31578947, 0.36842105],
       [0.42105263, 0.47368421, 0.52631579, 0.57894737],
       [0.63157895, 0.68421053, 0.73684211, 0.78947368],
       [0.84210526, 0.89473684, 0.94736842, 1.        ]])

In [9]:
#  spliting the vector into three arrays by taking the first 15, follow by the next 20 and the remaining into another variable
first, second, third = np.vsplit(val1, [2,4])
print("var1\n",first)
print("var2\n", second)
print("var3\n",third)

var1
 [[0.         0.05263158 0.10526316 0.15789474]
 [0.21052632 0.26315789 0.31578947 0.36842105]]
var2
 [[0.42105263 0.47368421 0.52631579 0.57894737]
 [0.63157895 0.68421053 0.73684211 0.78947368]]
var3
 [[0.84210526 0.89473684 0.94736842 1.        ]]


In [8]:
x1, x2, x3 = np.split(vect, (15,35))
print(x1, x2, x3)

[0.         0.02040816 0.04081633 0.06122449 0.08163265 0.10204082
 0.12244898 0.14285714 0.16326531 0.18367347 0.20408163 0.2244898
 0.24489796 0.26530612 0.28571429] [0.30612245 0.32653061 0.34693878 0.36734694 0.3877551  0.40816327
 0.42857143 0.44897959 0.46938776 0.48979592 0.51020408 0.53061224
 0.55102041 0.57142857 0.59183673 0.6122449  0.63265306 0.65306122
 0.67346939 0.69387755] [0.71428571 0.73469388 0.75510204 0.7755102  0.79591837 0.81632653
 0.83673469 0.85714286 0.87755102 0.89795918 0.91836735 0.93877551
 0.95918367 0.97959184 1.        ]


In [12]:
# 4x5 manually
val3 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]])
val3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [7]:
# Generating 4x5 array using random generated value between 0 and 1
ARRAY=np.random.random((4,5))
ARRAY

array([[0.78909961, 0.88786918, 0.59714975, 0.27818333, 0.73119569],
       [0.42644428, 0.28496014, 0.16332722, 0.99878763, 0.08347341],
       [0.15035436, 0.20452726, 0.73269908, 0.14073774, 0.92391022],
       [0.87825334, 0.10354733, 0.84461895, 0.61688982, 0.28969941]])

In [9]:
# Generating 4x5 array using array of ones
np.ones((4,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])